export {
  type ByteArray,
  type ScanFilter,
  type BLEDevice,
  type ScanCallback,
  type ManufacturerDataEntry,
  type ManufacturerData,
  type ServiceDataEntry,
  type ServiceData,
  type ConnectionCallback,
  type DisconnectEventCallback,
  type OperationCallback,
  type CharacteristicUpdateCallback,
  type Subscription,
  type AsyncSubscription,
  type BleNitroManagerOptions,
  type BlePermissionOptions,
  type BlePermissionStatus,
  type GattServerCharacteristic,
  type GattServerAdvertisingCallback,
  type GattServerCharacteristicReadCallback,
  type GattServerCharacteristicReadEvent,
  type GattServerCharacteristicWriteCallback,
  type GattServerCharacteristicWriteEvent,
  type GattServerDeviceCallback,
  type GattServerDeviceEvent,
  type GattServerErrorCallback,
  type GattServerErrorEvent,
  type GattServerNotificationOptions,
  type GattServerNotificationResult,
  type GattServerMtuCallback,
  type GattServerMtuEvent,
  type GattServerAdvertisingOptions,
  type GattServerAndroidAdvertisingOptions,
  type GattServerOptions,
  type GattServerService,
  type GattServerSubscriptionCallback,
  type GattServerSubscriptionEvent,
  BLEState,
  AndroidScanMode,
  AndroidConnectionPriority,
  GattCharacteristicPermission,
  GattCharacteristicProperty,
  GattServerAdvertiseMode,
  GattServerAdvertiseTxPowerLevel,
  BleNitroManager,
  BleTimeoutError,
} from "./manager";

export { BleNitro } from './singleton';
